version: '3.8'
services:
  mysql:
    build: 
      context: /mysql
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      MYSQL_DATABASE: "url_shortener"
      MYSQL_USER: "hey"
      MYSQL_PASSWORD: "your_user_password"
      MYSQL_ROOT_PASSWORD: "your_root_password"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "hey", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - app-network
  node-app1:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://hey:your_user_password@mysql:3306/url_shortener
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
  nginx:
    build:
      context: /nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app1
    networks:
      - app-network
networks:
  app-network:
    driver: bridge