-- CreateTable
CREATE TABLE User (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(191) NOT NULL UNIQUE,
  createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  userType ENUM('TRADITIONAL', 'OAUTH') NOT NULL
);

CREATE TABLE Url (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  longUrl TEXT NOT NULL,
  shortUrl VARCHAR(255) NOT NULL UNIQUE,
  createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  idUser INT,
  FOREIGN KEY (idUser) REFERENCES User(id)
);

CREATE TABLE TraditionalUser (
  idUser INT NOT NULL PRIMARY KEY,
  password VARCHAR(191) NOT NULL,
  verifiedAt TIMESTAMP(6),
  FOREIGN KEY (idUser) REFERENCES User(id)
);

CREATE TABLE OauthUser (
  idUser INT NOT NULL PRIMARY KEY,
  isVerified BOOLEAN NOT NULL,
  FOREIGN KEY (idUser) REFERENCES User(id)
);

CREATE TABLE VerificationToken (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  idUser INT NOT NULL,
  token VARCHAR(191) NOT NULL,
  tokenExpire TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (idUser) REFERENCES TraditionalUser(idUser)
);